# server config
server:
  session:
    timeout: 1800
  port: 8080

#JDBC
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#    Druid 连接池配置
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20

#      Druid监控配置
      web-stat-filter:
        enabled: true
#        exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
      stat-view-servlet:
        login-username: druid
        login-password: druid

# encoding
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

# upload file
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB


# view
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp


# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


# 打印sql
logging:
  level:
      com.sjz.dao: debug
# config: classpath:logback.xml


# 小程序配置
miniapp:
  appId: appId
  appsecret: appsecret